---

- name: Ensure OpenSSH support is installed
  yum:
    name: '{{ item }}'
    state: '{{ "present"
               if (ansible_local|d() and ansible_local.sshd|d())
               else "latest" }}'
  with_flattened:
    - sshd_base_packages
    - sshd_packages

- name: Get list of available host keys
  shell: find /etc/ssh -maxdepth 1 -type f -name 'ssh_host_*_key.pub' -exec basename {} .pub \;
  register: sshd_register_host_keys
  changed_when: False
  tags: [ 'role::sshd:config' ]

- name: Setup /etc/ssh/sshd_config
  template:
    src:    "{{ lookup('template_src', 'etc/ssh/sshd_config.j2') }}"
    dest:   '/etc/ssh/sshd_config'
    owner:  'root'
    group:  'root'
    mode:   '0644'
  notify: [ 'Test sshd configuration and restart' ]
  tags: [ 'role::sshd:config' ]

- name: Make sure the system-wide known_hosts file exists
  copy:
    force:    False
    dest:     '{{ sshd_known_hosts_file }}'
    content:  ''
    owner:    'root'
    group:    'root'
    mode:     '0644'
  tags: [ 'role::sshd:known_hosts' ]

- name: Get list of already scanned host fingerprints
  shell: ssh-keygen -f {{ sshd_known_hosts_file }} -F {{ item }} | grep -q '^# Host {{ item }} found'
  with_flattened:
    - sshd_known_hosts
    - sshd_group_known_hosts
    - sshd_host_known_hosts
  when: item is defined and item
  register: sshd_register_known_hosts
  changed_when: False
  failed_when: False
  tags: [ 'role::sshd:known_hosts' ]

- name: Scan SSH fingerprints of specified hosts
  shell: '{{ sshd_known_hosts_command }} {{ item.item }} >> {{ sshd_known_hosts_file }}'
  with_items: sshd_register_known_hosts.results
  when: item is defined and item.rc > 0
  tags: [ 'role::sshd:known_hosts' ]

- name: Make sure that Ansible local fact directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Write Ansible local facts
  template:
    src: 'etc/ansible/facts.d/sshd.fact.j2'
    dest: '/etc/ansible/facts.d/sshd.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'

